# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: detekt run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazoncorretto:11.0.11
      env:
        # コンテナ内では`~`が`/github/home`となるため、キャッシュディレクトリの辻褄をここで合わせる
        GRADLE_USER_HOME: /github/home/.gradle

    steps:
      # actions/checkout@v2の実行のため、コンテナ内に少なくともtarコマンドが必要
      # actions/cache@v1の実行のため、コンテナ内にtar, gzipコマンドが必要
      - name: Install tar, gzip for actions/checkout and actions/cache
        run: yum install -y tar gzip

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: test code execute
        run: ./gradlew detekt

      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif
